# Generated by Django 3.2.15 on 2022-09-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_commetspost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommetsPost',
        ),
    ]
